name: Update

on:
  push:
    branches:
      - "main"

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PULUMI_CONFIG_PASSPHRASE: ""

jobs:
  main:
    runs-on: ubuntu-latest
    name: Update
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6

      - name: Build Binary
        run: |
          go mod tidy
          go build main.go         

      - name: Pulumi Preview
        uses: pulumi/actions@v4
        with:
          command: up
          refresh: true
          stack-name: dev
          cloud-url: s3://tiexin-pulumi-test-state
